codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "50...80"

  status:
    project:
        threshold: 0.05
    patch:
        threshold: 100
    changes:
        threshold: 50
