#!/usr/bin/env python
# coding: utf-8
from matador.scrapers.cif_scraper import cif2dict
from matador.export import doc2res
from matador.utils.print_utils import print_notify, print_success, print_failure
from sys import argv

fnames = argv[1:]
for fname in fnames:
    print_notify("Reading " + fname)
    doc, success = cif2dict(fname)
    if success:
        doc2res(doc, fname.replace(".cif", ".res"), spoof_titl=True)
        print_success("Wrote .res file to " + fname.replace(".cif", "") + ".res")
    else:
        print(doc)
        print_failure("Unable to read structure in " + fname + ".")
