#!/usr/bin/env python
""" Quick script to compute overlap and plot PDFs from CLI. """
from sys import argv
from matador.scrapers.castep_scrapers import res2dict
from matador.similarity.pdf_similarity import PDF, PDFOverlap

strucs = []
overlaps = []
for res in argv[1:]:
    struc, success = res2dict(res, db=False)
    if not success:
        print(struc)
        exit()
    else:
        strucs.append(struc)

for i in range(len(strucs)):
    strucs[i]['text_id'] = [strucs[i]['source'][0].split('/')[-1].replace('_', ' ').replace('.res', ''), '']
    strucs[i]['pdf'] = PDF(strucs[i], dr=0.01, debug=False, verbosity=0)

print('Similarity distances between PDFs:\n')
for i in range(len(strucs)):
    for j in range(i+1, len(strucs)):
        overlaps.append(PDFOverlap(strucs[i]['pdf'], strucs[j]['pdf'], projected=False))

overlaps = sorted(overlaps, key=lambda x: x.similarity_distance)

width = 92
print('┌' + 7*'─' + '┬' + 42*'─' + '┬' + 41*'─' + '┐')
for overlap in overlaps:
    print('│{:>6.4f} │ {:^40} │ {:^40}│'
          .format(overlap.similarity_distance, overlap.pdf_A.label, overlap.pdf_B.label))

print('└' + 7*'─' + '┴' + 42*'─' + '┴' + 41*'─' + '┘')

strucs[0]['pdf'].plot_pdf(other_pdfs=[doc['pdf'] for doc in strucs[1:]])
for overlap in overlaps:
    overlap.plot_diff()
