#!/usr/bin/env python
# coding: utf-8
from matador.scrapers import castep_scrapers
from ase.io import write
from matador.utils.viz_utils import doc2ase
from matador.utils.print_utils import print_notify, print_success, print_failure
from sys import argv

fnames = argv[1:]
for fname in fnames:
    print_notify("Reading " + fname)
    res_dict, success = castep_scrapers.res2dict(fname, db=False)
    ase_doc = doc2ase(res_dict)
    if success:
        write(fname.replace(".res", ".cif"), ase_doc, format="cif")
        print_success("Wrote .cif file to " + fname.replace(".res", "") + ".cif")
    else:
        print_failure("Unable to find final structure in " + fname + ".")
print_success("Completed!")
